### PR TITLE
Adds support for entity binary_sensor

### PR DESCRIPTION
**Pull request by rforro**
I couldn't stop and programmed the binary sensor (see #16) as well. Because this cannot be set, only read, `toggleEntityState` never reaches `setEntityState`.

### CODE REVIEW

**Comment by karlenek** [comment]
The problem with having sensors is that there is currently no way to refresh the state other than restarting the widget or going into settings and pressing refresh. I think that instead of ignoring the select button, maybe we could refresh the selected entity instead?

**Comment by rforro** [comment]
It can be an option, but from the UI point of view it is a bit different behaviour as expected. All supported entities change their state by clicking on them but this one.

Actually I was thinking more globally about refreshing the state of all entities. I think it should happens more twice (while starting and manually from menu). (as I wrote in the FAQs, currently there is this possibility to get any entity out of sync)
Currently I see 2 possible solutions:

1. Periodically (every 15 sec?) refresh state of all entities. I think the Hassiq uses this method.
2. At every "scroll" request current state of opened entity from HASS. I looked at HASS REST API and they are returning `last_updated` value as well, which can be compared with value stored in the widget. Only if there is a difference the state will be updated.

**Comment by karlenek** [comment]
I agree with you, it's a bit different behavior and might not be the best solution.

I think refreshing every time an entity comes into focus is a good idea. We could wait for a second and if the "new" entity is still in focus we could refresh it.

The reason I decided to not refresh automatically was only due to the limited battery and that I'm unsure how it affects the automatic termination of the widget. Will Garmin still terminate the widget even though there are som requests going on? Maybe they are only watching user interaction and not background refresh etc.

**Comment by rforro** [comment]
> 
> 
> I agree with you, it's a bit different behavior and might not be the best solution.
> 
> I think refreshing every time an entity comes into focus is a good idea. We could wait for a second and if the "new" entity is still in focus we could refresh it.

Good catch I totally forgot, that if you just scroll through entities it will immediately trigger a request.

> The reason I decided to not refresh automatically was only due to the limited battery and that I'm unsure how it affects the automatic termination of the widget. Will Garmin still terminate the widget even though there are som requests going on? Maybe they are only watching user interaction and not background refresh etc.

I'm pretty sure that Garmin power saving policy is very strict and I don't think that `timer` or `request` will block widgets timeout. This "hypothesis" can be easily tested, I can do it.

Actually I don't think that periodic refreshing is the way. We cannot compared how is used the HASS app on mobile phone and Hasscontrol. On mobile phone, when I open the app, I check most of my entities, history, cameras etc. But on a watch not more than a few seconds (check temperature, turn on the light and done). I don't think that average user uses Hasscontrol for more than a few seconds during one session.

**Review by karlenek — APPROVED** [review]

**Pull request merged**
